### ISSUE TITLE
Can we set the index of the button bar programmatically? 

### ISSUE THREAD

**Issue by ganapathyp** [JorisObert/animated_button_bar#1]

**Comment by JorisObert** [comment]
Could you test this branch and tell me if it fits your need ? I added an optional AnimatedButtonController that can `setIndex`

```
animated_button_bar:
    git:
      url: https://github.com/JorisObert/animated_button_bar.git
      ref: controller
```

See the example for usage, pretty straightforward.
